version: '{build}'  
image: 
  - Visual Studio 2017
  - Ubuntu
pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - master
nuget:  
  disable_publish_on_pr: true
environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
build_script:  
- ps: .\build.ps1
- sh: ./build.sh
test: off  
artifacts:  
- path: .\artifacts\**\*.nupkg
  name: NuGet
for:
-
  matrix:
    only:
      - image: Ubuntu
  deploy:
  - provider: NuGet
    server: https://www.myget.org/F/kedzior-io-connectionstringconverter/api/v2/package
    name: production
    api_key:
      secure: tOQ2rz+MUX9sYoE/eJC6jlVNgj9qTNahGVvLYAVMX+si9Hr4/0IzCHEKWvtNMtli
    on:
      branch: master
      appveyor_repo_tag: true